---
baseurl: "https://note.xxend.cool/"
DefaultContentLanguage: "zh-cn"
hasCJKLanguage: true
languageCode: "zh-cn"
title: "XX笔记"
theme: "bilberry-hugo-theme/v4"
metaDataFormat: "yaml"
algolia:
  index: "xxnote"
  key: "f4b0adca6c546597334977461b4539d9"
  appID: "9ZGP1NUCW2"
---
